title: Yipeng Zou
logo: /assets/img/my.jpg
description: ""
show_downloads: False
show_links: True
google_analytics:
theme: jekyll-theme-minimal
i18n: true

email: "mailto:zouyipeng32@outlook.com"
github: "https://github.com/zouyipeng"
email_icon: "/assets/img/email.svg"
github_icon: "/assets/img/github.svg"

skills:
  - C
  - Assembly (ARM)
  - Python
  - Linux Kernel
  - FreeRTOS
  - ARM64
  - Git
  - GDB
  - Make
  - vibe code
  - JTAG/SWD
